[cargo]
target = "xtensa-esp32-none-elf"
extraArgs = ["-Zbuild-std=core,alloc"]

[check]
command = "check"
extraArgs = ["-Zbuild-std=core,alloc"]
allTargets = false

[server]
extraEnv = { RUSTUP_TOOLCHAIN = "esp" }
