[package]
edition = "2024"
name = "esp32-rust-project"
rust-version = "1.88"
version = "0.1.0"

[[bin]]
name = "esp32-rust-project"
path = "./src/bin/main.rs"
test = false

[lib]
test = false
doctest = false

[dependencies]
rubicson = { path = "../crates/rubicson" }
eu-dst = { path = "../crates/eu-dst" }

defmt = "1.0.1"
esp-hal = { version = "~1.0", features = ["defmt", "esp32", "unstable"] }
esp-rtos = { version = "0.2.0", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp32",
  "esp-radio",
] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["defmt", "esp32"] }
embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-futures = { version = "0.1.1" }
embassy-net = { version = "0.8.0", features = ["defmt", "tcp", "udp", "dhcpv4", "medium-ethernet"] }
esp-alloc = { version = "0.9.0", features = ["defmt"] }
esp-println = { version = "0.16.1", features = ["esp32", "defmt-espflash"] }
esp-radio = { version = "0.17.0", features = [
  "esp32",
  "wifi",
  "smoltcp",
  "defmt",
  "unstable",
] }
rtt-target = { version = "0.6.2", features = ["defmt"] }
critical-section = "1.2.0"
static_cell = "2.1.1"
embedded-hal = "1.0"
embedded-hal-bus = { version = "0.3.0", features = ["defmt-03"] }
embedded-io-async = "0.6"
esp-sync = { version = "0.1.1", features = ["esp32"] }
cc1101 = { git = "https://github.com/dsvensson/cc1101.git", branch = "main" }
rust-mqtt = { version = "0.4", default-features = false, features = ["defmt", "v5", "bump"] }
heapless = "0.8"
xtensa-lx = "0.13.0"

# Display
mini-oled = "0.1"
embedded-graphics = "0.8"
profont = "0.7"

# Time sync
sntpc = { version = "0.8", default-features = false }
sntpc-net-embassy = "0.8"
